language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm@6.1.0
  - npm install
dist: trusty
script:
  - echo "skipping tests"
before_deploy:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm run build
deploy:
  provider: s3
  region: us-east-2
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
